POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json

{
    "email": "guest1@email.com",
    "password": "abc123"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json

{
    "email": "guest1@email.com",
    "password": "abc123"
}

###

POST https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzLCJlbWFpbCI6Imd1ZXN0MUBlbWFpbC5jb20iLCJpYXQiOjE2NTAzMDUzMjJ9.3YXBVi668iWICfHMJIJtOJtKLdPXLJLkX76LKOrzKOo
Content-Type: application/json

{
    "title": "Still life commercial photography",
    "description": "Will bring dead things to life"
}

###

GET https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzMzLCJlbWFpbCI6Imd1ZXN0MUBlbWFpbC5jb20iLCJpYXQiOjE2NTAzMDUzMjJ9.3YXBVi668iWICfHMJIJtOJtKLdPXLJLkX76LKOrzKOo
###
